    graph
      A[handle] --> C(AirQuant)
      B[matlab.mixin.SetGet] --> C
      C --> D[Tube]
      C --> E[Network]
      D --> F[Airway]
      E --> G[ClinicalAirways]
      H[library]
      I[SuperMeasure] --> J[AirwayFWHMesl]
      L[AQEllipse]
