name: copyreadme
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: copy file
        uses: vodapay-gateway/github-action-copy@master
        with:
          source: "docs/index.rst"
          target: "readme.txt"
